# Generated by Django 6.0.3 on 2026-08-17 16:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('subject', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('status', models.CharField(default='open', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(default='Social Welfare', max_length=100)),
                ('ministry', models.CharField(default='Government of India', max_length=255)),
                ('gov_level', models.CharField(default='Central Government', max_length=50)),
                ('state_coverage', models.CharField(default='All India', max_length=100)),
                ('status', models.CharField(default='Applications Open', max_length=50)),
                ('objective', models.TextField(blank=True, default='')),
                ('description', models.TextField(blank=True, default='')),
                ('beneficiaries', models.TextField(blank=True, default='')),
                ('benefits_summary', models.CharField(default='', max_length=255)),
                ('benefits', models.JSONField(blank=True, default=list)),
                ('eligibility', models.JSONField(blank=True, default=list)),
                ('documents', models.JSONField(blank=True, default=list)),
                ('process', models.JSONField(blank=True, default=list)),
                ('deadline', models.CharField(default='Ongoing', max_length=100)),
                ('official_link', models.CharField(default='#', max_length=255)),
                ('contact_info', models.JSONField(blank=True, default=dict)),
                ('faqs', models.JSONField(blank=True, default=list)),
                ('ai_score', models.IntegerField(default=95)),
                ('ai_checklist', models.JSONField(blank=True, default=list)),
                ('estimated_benefit', models.CharField(default='₹50,000', max_length=100)),
                ('target_occupations', models.JSONField(blank=True, default=list)),
                ('target_sectors', models.JSONField(blank=True, default=list)),
                ('max_income', models.IntegerField(default=1200000)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='Chetan Rawat', max_length=150)),
                ('email', models.CharField(db_index=True, max_length=150, unique=True)),
                ('phone', models.CharField(blank=True, default='+91 98765 43210', max_length=30)),
                ('password_hash', models.CharField(max_length=128)),
                ('role', models.CharField(choices=[('citizen', 'Citizen'), ('admin', 'Admin Officer')], default='citizen', max_length=20)),
                ('token', models.CharField(blank=True, default='', max_length=64)),
                ('otp_code', models.CharField(default='123456', max_length=10)),
                ('otp_created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('dob', models.CharField(blank=True, default='1998-06-14', max_length=30)),
                ('gender', models.CharField(default='Male', max_length=20)),
                ('state', models.CharField(default='Uttarakhand', max_length=100)),
                ('district', models.CharField(default='Dehradun', max_length=100)),
                ('address', models.TextField(blank=True, default='14, Rajpur Road, Dehradun, Uttarakhand — 248001')),
                ('occupation', models.CharField(default='Farmer', max_length=50)),
                ('income', models.IntegerField(default=285000)),
                ('education', models.CharField(default='12th Pass', max_length=50)),
                ('category', models.CharField(default='OBC', max_length=30)),
                ('has_disability', models.BooleanField(default=False)),
                ('disability_type', models.CharField(blank=True, default='', max_length=100)),
                ('disability_pct', models.IntegerField(default=0)),
                ('email_alerts', models.BooleanField(default=True)),
                ('sms_alerts', models.BooleanField(default=True)),
                ('share_profile', models.BooleanField(default=False)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SchemeUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ministry_or_node', models.CharField(default='State Welfare Department', max_length=150)),
                ('change_summary', models.TextField()),
                ('status', models.CharField(default='pending', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='api.scheme')),
            ],
        ),
        migrations.CreateModel(
            name='SchemeReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issues', models.JSONField(default=list)),
                ('details', models.TextField(blank=True)),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='api.scheme')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.useraccount')),
            ],
        ),
        migrations.CreateModel(
            name='SchemeFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=5)),
                ('feedback_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='api.scheme')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.useraccount')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('scheme_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='submitted', max_length=30)),
                ('stage', models.IntegerField(default=0)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('applicant_data', models.JSONField(blank=True, default=dict)),
                ('submitted_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('scheme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='api.scheme')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='api.useraccount')),
            ],
        ),
        migrations.CreateModel(
            name='UserDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_key', models.CharField(default='Identity', max_length=50)),
                ('doc_type_name', models.CharField(default='Government Document', max_length=150)),
                ('category', models.CharField(default='mandatory', max_length=50)),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('file_name', models.CharField(default='document.pdf', max_length=255)),
                ('file_size', models.CharField(default='1.2 MB', max_length=50)),
                ('file_format', models.CharField(default='PDF Document', max_length=50)),
                ('status', models.CharField(default='Verified', max_length=50)),
                ('admin_notes', models.TextField(blank=True, default='')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='api.useraccount')),
            ],
        ),
        migrations.CreateModel(
            name='SchemeBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='api.scheme')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='api.useraccount')),
            ],
            options={
                'unique_together': {('user', 'scheme')},
            },
        ),
    ]
