# Generated by Django on 2026-08-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheme',
            name='scheme_code',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='full_name',
            field=models.CharField(default='Citizen User', max_length=150),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='dob',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='state',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='district',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='occupation',
            field=models.CharField(default='General', max_length=50),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='income',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='education',
            field=models.CharField(default='General', max_length=50),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='category',
            field=models.CharField(default='General', max_length=30),
        ),
    ]
